[project]
name = "asynkaf"
version = "0.1.0"
description = "High-performance asyncio Kafka client"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "YangYounghwa" }]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
